create table if not exists public.check_ins (
  id bigint generated by default as identity primary key,
  person text not null check (person in ('Emily', 'Evan')),
  mood text not null check (mood in ('good', 'bad')),
  answer text not null,
  created_at timestamptz not null default now()
);

alter table public.check_ins enable row level security;

grant select, insert on public.check_ins to anon;

drop policy if exists "Anyone can read check-ins" on public.check_ins;
drop policy if exists "Anyone can read recent check-ins" on public.check_ins;
create policy "Anyone can read recent check-ins"
  on public.check_ins
  for select
  to anon
  using (created_at >= now() - interval '12 hours');

drop policy if exists "Anyone can submit check-ins" on public.check_ins;
create policy "Anyone can submit check-ins"
  on public.check_ins
  for insert
  to anon
  with check (true);
